name: Build and Push Release Binary

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Build and Run Trainer
        run: cargo run --release -p cli -- -c 10000

      - name: Build web_server
        run: cargo build --release -p web_server

      - name: Copy WebServer via ssh
        uses: garygrossgarten/github-action-scp@release
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: ${{ secrets.AZURE_VM_USER  }}
          privateKey: ${{ secrets.AZURE_VM_SSH_KEY }}
          port: ${{ secrets.AZURE_VM_PORT }}
          local: target/release/web_server
          remote: "/home/${{ secrets.AZURE_VM_USER }}/dynamic_pricing_optimizer/target/release"

      - name: Restart Native Service
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: ${{ secrets.AZURE_VM_USER  }}
          key: ${{ secrets.AZURE_VM_SSH_KEY }}
          port: ${{ secrets.AZURE_VM_PORT }}
          script: |
            sudo systemctl restart pricing_service.service
